server {
    listen 80;

    # Onde os arquivos do Angular vão ficar
    root /usr/share/nginx/html;
    index index.html index.htm;

    # O truque: Se não achar a rota, devolve o index.html e deixa o Angular se virar
    location / {
        try_files $uri $uri/ /index.html;
    }
}
