name: Deploy CadMed

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Conectando no Servidor e Atualizando
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd ~/CadMed
            git pull origin main
            docker compose build --no-cache
            docker compose up -d --force-recreate --remove-orphans
            docker image prune -f