name: Teste de Conexao SSH

on:
  push:
    branches:
      - main
      - master

jobs:
  testar:
    runs-on: ubuntu-latest
    steps:
      - name: Tentando entrar no GCP...
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            echo "A CONEXAO SSH FUNCIONOU PERFEITAMENTE!"
            pwd