name: Deploy CadMed

# 1. O Gatilho: Quando esse robô deve acordar?
on:
  push:
    branches:
      - main
      - master

# 2. As Tarefas: O que ele deve fazer?
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Conectando no Servidor e Atualizando
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd /home/gabrielnunesdossantoss/CadMed
            sudo git pull origin main
            sudo docker compose build --no-cache
            sudo docker compose up -d --force-recreate